# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('moment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SensorKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=5)),
                ('minValue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('maxValue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sensors', models.ManyToManyField(to='data.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sensor'),
        ),
        migrations.AddField(
            model_name='reading',
            name='sensorKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SensorKind'),
        ),
    ]
