# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorkind',
            name='maxValue',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sensorkind',
            name='minValue',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sensorkind',
            name='unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
