# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190108_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
